// Records confirmed as not belonging in a student scholarship directory
// (faculty/postdoc grants, internships, loans, organizational awards).
// Curated 2026-08-27 by a two-pass agent review; indexing owns this list --
// raw imports stay immutable. Remove an entry to restore its record.
export const EXCLUDED_RECORDS = new Map([
  ["careeronestop-06ff8e6df4fd6ad2", "Grant explicitly for faculty members to attend language courses, not students."],
  ["careeronestop-0db1c101bbf4c039", "Fellowship to help practicing surgeons build an independent research program, not a student scholarship."],
  ["careeronestop-0f0e897d484ae429", "Explicitly a faculty research grant, not a student scholarship."],
  ["careeronestop-101af0d090df8974", "Research residency fellowship for scholars using a library collection, not a student scholarship."],
  ["careeronestop-149759ca897aa7c3", "Research funding explicitly for young faculty, not students."],
  ["careeronestop-1632d77a8351be88", "Recognition grant for an association member's career contributions, not a student award."],
  ["careeronestop-1a1ea3e92d63600d", "Funding explicitly for faculty research working groups, not for students."],
  ["careeronestop-1e6d8cfd9c1ee7c2", "This is an internship program, not a scholarship."],
  ["careeronestop-20a5d72337093840", "Recognizes career service/volunteer contributions to the organization, not a student award."],
  ["careeronestop-23f6655fdadeb554", "Recognizes institutional innovations in graduate programs, not an award to individual students."],
  ["careeronestop-247896fb4ca1e3a3", "Internship placement in policy/communications departments, not a scholarship."],
  ["careeronestop-2693fcee41a9ee5d", "Explicitly for young surgeons pursuing academic/faculty careers, not a student scholarship."],
  ["careeronestop-27abfd9e2c610905", "Grant explicitly for individuals beginning independent research careers at the faculty level."],
  ["careeronestop-2c0ef61e7f6af3cd", "This is a loan product for residency costs, not a scholarship."],
  ["careeronestop-33531faca9bcaa65", "Explicitly an accounting internship/training program, not a scholarship."],
  ["careeronestop-4db54a937889b860", "Vague institutional support program for individuals and organizations aligned with agency strategic goals, not a student scholarship."],
  ["careeronestop-4fe2507d85851357", "Smithsonian aerospace history fellowship aimed at scholars/professionals, not undergraduate students."],
  ["careeronestop-55fbab2d3b5e4244", "This is a student loan product, not a scholarship."],
  ["careeronestop-58698ae37d64c649", "Title and description describe an internship program, not a scholarship."],
  ["careeronestop-58fabe50f968fbf8", "Research project funding at Professional Development level, not a student scholarship."],
  ["careeronestop-59cceeefcad7b3e9", "Research award for practicing academic surgeons, not a student scholarship."],
  ["careeronestop-5ca4da09cccb1f9f", "Funds programs addressing child abuse/neglect, not a scholarship for students."],
  ["careeronestop-5ff55487c1a9be94", "Explicitly a loan product, not a scholarship."],
  ["careeronestop-6f3f879b46fbf27f", "Fellowship restricted to ABD pre-doctoral candidates, postdocs, faculty and senior scholars, not undergraduate/early students."],
  ["careeronestop-81f33fe92727f3d9", "Explicitly a communications internship program."],
  ["careeronestop-8803edc8decd0643", "Award recognizing accredited sheriff's offices (organizations), not students."],
  ["careeronestop-88fbbd3022d22f37", "Explicitly an internship/work-experience program pairing youth with ranchers, not a scholarship."],
  ["careeronestop-8996cc064e42c49c", "Grant funds medical research institutions/professionals, not a student scholarship."],
  ["careeronestop-8c93ec97a0301afc", "Explicitly research funding for tenured/tenure-track faculty members."],
  ["careeronestop-8e4960ccf115711a", "This is a paid/unpaid internship (on-job training), not a scholarship award."],
  ["careeronestop-9bc3e8b8d2ea503b", "Explicitly a loan product, not a scholarship."],
  ["careeronestop-af8c2fc3a928c26d", "Explicitly for junior faculty (not fellows) with research track records, not students."],
  ["careeronestop-b30c9710d4e0c44c", "Community foundation grant for local programs/services, not an individual student scholarship."],
  ["careeronestop-b4eb276f124bc131", "This is a loan product, not a scholarship."],
  ["careeronestop-bae0c85d71b258f9", "Salary/benefit support for licensed Nurse Practitioners or PAs in clinical training, not a student scholarship."],
  ["careeronestop-bec3d13ab042a6c5", "Postdoctoral fellowship, not relevant to high school or undergraduate students."],
  ["careeronestop-c072d3d7a3b2d984", "Grant to support civil society organizations in Afghanistan, not a student scholarship."],
  ["careeronestop-c47d2a8c84c1fd1f", "Legal internship for law students/graduates, not a scholarship."],
  ["careeronestop-d2a3e41cc1e61f13", "Professional development grant for working hospital librarians, not a student scholarship."],
  ["careeronestop-d61a141d27d8684d", "Postdoctoral fellowship for scientists transitioning to faculty positions, not for students."],
  ["careeronestop-da609f10be67b324", "Research grant restricted to Professional Development level (practicing endodontists), not a student scholarship."],
  ["careeronestop-dad218f35010d04b", "Award to school districts for safety programs, not to individual students."],
  ["careeronestop-e2d9bb79fc2f97f2", "Seed grant explicitly for junior faculty and research scientists, not students."],
  ["careeronestop-f3a833df1d1a4492", "Explicitly a grant for the chapter's faculty advisor, not a student award."],
  ["careeronestop-f7ddcde83a992388", "This is a student loan product, not a scholarship."],
]);
